import { createFileRoute, Link } from "@tanstack/react-router";
import { Footer } from "@/components/ghost/Footer";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [{ title: "Terms of Service — Idle Check" }],
  }),
  component: TermsOfService,
});

function TermsOfService() {
  return (
    <div className="relative flex min-h-screen flex-col bg-background text-foreground">
      <main className="mx-auto w-full max-w-2xl flex-1 px-4 py-16 sm:px-6">
        <Link to="/" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors mb-8">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m15 18-6-6 6-6"/></svg>
          Back
        </Link>
        <p className="font-condensed text-xs font-semibold uppercase tracking-[0.16em] text-primary">
          Legal
        </p>
        <h1 className="mt-3 text-3xl font-extrabold tracking-tight">Terms of Service</h1>
        <p className="mt-2 text-[13px] text-muted-foreground">Last updated: June 2026</p>

        <div className="mt-10 space-y-8 text-[14px] leading-relaxed text-foreground">

          <section className="space-y-3">
            <h2 className="font-condensed text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">
              1. Acceptance of Terms
            </h2>
            <p>
              By using Idle Check ("the Service"), you agree to these Terms of Service. If you do
              not agree, do not use the Service. These terms apply to all users of idlecheck.com
              and any related services.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-condensed text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">
              2. Description of Service
            </h2>
            <p>
              Idle Check is an AI-powered vehicle listing analysis tool. Users paste used car
              listing text and receive an inspection report containing potential issues, estimated
              repair costs, NHTSA recall data, and a negotiation script. Three findings are
              provided free of charge. A full report requires a one-time payment of $4.99.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-condensed text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">
              3. Disclaimer of Warranties
            </h2>
            <p className="font-medium text-foreground">
              THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND.
            </p>
            <p>
              Idle Check reports are generated by AI and based on publicly available repair data
              and model-specific failure patterns. They are for informational purposes only and
              do not constitute professional mechanical advice. We make no representations or
              warranties regarding the accuracy, completeness, or fitness for purpose of any
              report.
            </p>
            <p>
              Always have any used vehicle inspected by a licensed, certified mechanic (ASE or
              equivalent) before purchase. A professional pre-purchase inspection supersedes any
              Idle Check report.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-condensed text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">
              4. Limitation of Liability
            </h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IDLE CHECK AND ITS OPERATORS
              SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
              PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, OR GOODWILL,
              ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE.
            </p>
            <p>
              Our total liability to you for any claim arising from use of the Service shall not
              exceed the amount you paid for the report giving rise to the claim (maximum $4.99).
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-condensed text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">
              5. Payments and Refunds
            </h2>
            <p>
              Full reports are available for a one-time payment of $4.99 USD, processed by
              Stripe. Payments are non-refundable once the full report has been delivered, except
              where required by applicable law. If you experience a technical issue preventing
              report delivery, contact us at idlecheckapp@gmail.com within 7 days for a full refund.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-condensed text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">
              6. Acceptable Use
            </h2>
            <p>You agree not to:</p>
            <ul className="list-none space-y-2 pl-4">
              {[
                "Use the Service for any unlawful purpose",
                "Attempt to reverse-engineer, scrape, or automate requests to the Service",
                "Submit false, misleading, or fraudulent listing data",
                "Resell or redistribute reports without written permission",
                "Attempt to circumvent the paywall through technical means",
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-2.5">
                  <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="font-condensed text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">
              7. Intellectual Property
            </h2>
            <p>
              The Idle Check name, logo, and report format are proprietary. The content of
              individual reports generated for you may be used for your personal vehicle purchase
              decisions. You may not republish or commercialize report content without written
              permission.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-condensed text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">
              8. Third-Party Services
            </h2>
            <p>
              The Service uses Anthropic Claude (AI analysis), NHTSA public API (recall data),
              and Stripe (payments). Use of these services is subject to their respective terms.
              We are not responsible for the availability or accuracy of third-party data,
              including NHTSA recall records.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-condensed text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">
              9. Governing Law
            </h2>
            <p>
              These Terms are governed by the laws of the Czech Republic, without regard to
              conflict of law principles. Any disputes arising from use of the Service shall be
              resolved in the courts of the Czech Republic.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-condensed text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">
              10. Changes to Terms
            </h2>
            <p>
              We reserve the right to modify these Terms at any time. The "Last updated" date
              will reflect changes. Continued use of the Service after changes constitutes
              acceptance of the updated Terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-condensed text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">
              11. Contact
            </h2>
            <p>
              For questions about these Terms, contact us at{" "}
              <a href="mailto:idlecheckapp@gmail.com" className="text-primary hover:underline">
                idlecheckapp@gmail.com
              </a>.
            </p>
          </section>

        </div>
      </main>
      <Footer />
    </div>
  );
}