/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as CarsSlugRouteImport } from './routes/cars/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsSlugRoute = CarsSlugRouteImport.update({
  id: '/cars/$slug',
  path: '/cars/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/report/$id': typeof ReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/report/$id': typeof ReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/report/$id': typeof ReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/privacy' | '/terms' | '/cars/$slug' | '/report/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/privacy' | '/terms' | '/cars/$slug' | '/report/$id'
  id: '__root__' | '/' | '/privacy' | '/terms' | '/cars/$slug' | '/report/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  CarsSlugRoute: typeof CarsSlugRoute
  ReportIdRoute: typeof ReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$slug': {
      id: '/cars/$slug'
      path: '/cars/$slug'
      fullPath: '/cars/$slug'
      preLoaderRoute: typeof CarsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  CarsSlugRoute: CarsSlugRoute,
  ReportIdRoute: ReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
